4Healthy²/Models/Alimento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _4Healthy_.Models
{
    public class Alimento
    {
        public int AlimentoId { get; set; }
        public string Descricao { get; set; }
        public int CategoriaId { get; set; }
        public Categoria Categoria { get; set; }
        public int Calorias { get; set; }
        public int Carboidratos { get; set; }
        public int Proteinas { get; set; }
        public int Gorduras { get; set; }
    }
}

4Healthy²/Controllers/AlimentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4Healthy_.Contexts;
using _4Healthy_.Models;

namespace _4Healthy_.Controllers
{
    public class AlimentosController : Controller
    {
        private EFContext db = new EFContext();

        // GET: Alimentos
        public ActionResult Index()
        {
            var alimento = db.Alimento.Include(a => a.Categoria);
            return View(alimento.ToList());
        }

        // GET: Alimentos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alimento alimento = db.Alimento.Find(id);
            if (alimento == null)
            {
                return HttpNotFound();
            }
            return View(alimento);
        }

        // GET: Alimentos/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(db.Categoria, "CategoriaId", "Nome");
            return View();
        }

        // POST: Alimentos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlimentoId,Descricao,CategoriaId,Calorias,Carboidratos,Proteinas,Gorduras")] Alimento alimento)
        {
            if (ModelState.IsValid)
            {
                db.Alimento.Add(alimento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(db.Categoria, "CategoriaId", "Nome", alimento.CategoriaId);
            return View(alimento);
        }

        // GET: Alimentos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alimento alimento = db.Alimento.Find(id);
            if (alimento == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categoria, "CategoriaId", "Nome", alimento.CategoriaId);
            return View(alimento);
        }

        // POST: Alimentos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlimentoId,Descricao,CategoriaId,Calorias,Carboidratos,Proteinas,Gorduras")] Alimento alimento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categoria, "CategoriaId", "Nome", alimento.CategoriaId);
            return View(alimento);
        }

        // GET: Alimentos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alimento alimento = db.Alimento.Find(id);
            if (alimento == null)
            {
                return HttpNotFound();
            }
            return View(alimento);
        }

        // POST: Alimentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alimento alimento = db.Alimento.Find(id);
            db.Alimento.Remove(alimento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4Healthy²/Views/Alimentos/Create.cshtml
@model _4Healthy_.Models.Alimento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alimento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calorias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calorias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calorias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carboidratos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carboidratos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carboidratos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Proteinas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Proteinas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Proteinas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gorduras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gorduras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gorduras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

4Healthy²/Views/Alimentos/Delete.cshtml
@model _4Healthy_.Models.Alimento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Você deseja mesmo deletar esse alimento?</h3>
<div>
    <h4>Alimento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carboidratos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carboidratos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proteinas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proteinas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorduras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gorduras)
        </dd>

    </dl>

        @Html.AntiForgeryToken()
        <div class="panel-footer panel-info">
            <a href="#" class="btn btn-info" data-toggle="modal"
               data-target="#deleteConfirmationModal">Remover</a>
            @Html.ActionLink("Retornar para a listagem", "Index",
                null, new { @class = "btn btn-info" })
        </div>
        <div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
             role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-ELTEismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h4 class="modal-title">
                            Confirmação de exclusão de
                        </h4>
                    </div>
                    <div class="modal-body">
                        <p>
                            Você está prestes a remover o Alimento @Model.Descricao do cadastro.
                        </p>
                        <p>
                            <strong>
                                Você está certo que deseja prosseguir?
                            </strong>
                        </p>
                        @using (Html.BeginForm("Delete", "Alimentos",
                            FormMethod.Post, new
                            {
                                @id = "delete-form",
                                role = "form"
                            }))
                        {
                            @Html.HiddenFor(m => m.Descricao)
                            @Html.AntiForgeryToken()
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                onclick="$('#delete-form').submit();">
                            Sim, exclua este produto.
                        </button>
                        <button type="button" class="btn btn-primary"
                                data-dismiss="modal">
                            Não, não exclua este produto.
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>

4Healthy²/Views/Alimentos/Details.cshtml
@model _4Healthy_.Models.Alimento

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Alimento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carboidratos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carboidratos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proteinas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proteinas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gorduras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gorduras)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AlimentoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

4Healthy²/Views/Alimentos/Edit.cshtml
@model _4Healthy_.Models.Alimento

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alimento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlimentoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calorias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calorias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calorias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carboidratos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carboidratos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carboidratos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Proteinas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Proteinas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Proteinas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gorduras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gorduras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gorduras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

4Healthy²/Views/Alimentos/Index.cshtml
@model IEnumerable<_4Healthy_.Models.Alimento>
@{
    ViewBag.Title = "Index";
    
}
<h2>Alimentos</h2>
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de Alimentos cadastrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Categoria.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Descricao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Calorias)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Carboidratos)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Proteinas)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Gorduras)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Calorias)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Carboidratos)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Proteinas)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gorduras)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.AlimentoId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.AlimentoId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.AlimentoId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar um novo Alimento","Create", null, new
{ @class ="btn btn-success" })
    </div>
    </div>
        @section styles{
            <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />
        }
        @section ScriptPage {
            <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
            <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('.table').dataTable();
                });
            </script>
        }

4Healthy²/Views/Alimentos/_ByAlimentos.cshtml
@model IEnumerable<_4Healthy_.Models.Alimento>
<div>
    <Strong>
        Alimento
    </Strong>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Relação de Alimentos cadastrados
        </div>
        <div class="panel-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Descricao)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Calorias)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Carboidratos)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Proteinas)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gorduras)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descricao)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Calorias)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Carboidratos)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Proteinas)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gorduras)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>