4Healthy²/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _4Healthy_.Models
{
    public class Categoria
    {
        public int CategoriaId { get; set; }
        public string Nome { get; set; }
        public virtual ICollection <Alimento> Alimentos { get; set; }
    }
}

4Healthy²/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4Healthy_.Contexts;
using _4Healthy_.Models;

namespace _4Healthy_.Controllers
{
    public class CategoriasController : Controller
    {
        private EFContext db = new EFContext();

        // GET: Categorias
        public ActionResult Index()
        {
            return View(db.Categoria.ToList());
        }

        // GET: Categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Where(f => f.CategoriaId == id).Include("Alimentos.Categoria").First();
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoriaId,Nome")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Categoria.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoriaId,Nome")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = db.Categoria.Find(id);
            db.Categoria.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4Healthy²/Views/Categorias/Create.cshtml
@model _4Healthy_.Models.Categoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

4Healthy²/Views/Categorias/Delete.cshtml
@model _4Healthy_.Models.Categoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Você deseja deletar esta categoria?</h3>
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    @Html.AntiForgeryToken()
    <div class="panel-footer panel-info">
        <a href="#" class="btn btn-info" data-toggle="modal"
           data-target="#deleteConfirmationModal">Remover</a>
        @Html.ActionLink("Retornar para a listagem", "Index",
                null, new { @class = "btn btn-info" })
    </div>
    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
         role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-ELTEismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">
                        Confirmação de exclusão de
                    </h4>
                </div>
                <div class="modal-body">
                    <p>
                        Você está prestes a remover a Categoria @Model.CategoriaId do cadastro.
                    </p>
                    <p>
                        <strong>
                            Você está certo que deseja prosseguir?
                        </strong>
                    </p>
                    @using (Html.BeginForm("Delete", "Categorias",
                    FormMethod.Post, new
                    {
                        @id = "delete-form",
                        role = "form"
                    }))
                    {
                        @Html.HiddenFor(m => m.CategoriaId)
                        @Html.AntiForgeryToken()
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            onclick="$('#delete-form').submit();">
                        Sim, exclua este produto.
                    </button>
                    <button type="button" class="btn btn-primary"
                            data-dismiss="modal">
                        Não, não exclua este produto.
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

4Healthy²/Views/Categorias/Details.cshtml
@model _4Healthy_.Models.Categoria

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>

    <div>
        <dd>
            @Html.Partial("~/Views/Alimentos/_ByAlimentos.cshtml", Model.Alimentos.ToList())
        </dd>
    </div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CategoriaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />
}
@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table').dataTable();
        });
    </script>
}

4Healthy²/Views/Categorias/Edit.cshtml
@model _4Healthy_.Models.Categoria

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoriaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

4Healthy²/Views/Categorias/Index.cshtml
@model IEnumerable<_4Healthy_.Models.Categoria>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Categorias</h2>
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de Alimentos cadastrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.CategoriaId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.CategoriaId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.CategoriaId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar nova Categoria", "Create", null, new
   { @class = "btn btn-success" })
    </div>
</div>
@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet" />
}
@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table').dataTable();
        });
    </script>
}